[package]
name = "xtask"
version = "0.1.0"
edition = "2024"

[dependencies]
walkdir = "2.5"
syn = { version = "2.0", features = ["full", "extra-traits", "visit"] }
quote = "1.0"
petgraph = "0.8"
glob = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.21"
